# Generated by Django 6.1.1 on 2026-09-04 05:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Task name must look like '10a': a number followed by letters.",
                                regex="^\\d+[a-z]+$",
                            )
                        ],
                    ),
                ),
                ("selected", models.BooleanField(default=True)),
            ],
        ),
    ]
