# Generated by Django 6.1.1 on 2026-09-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("mou", "name"), name="unique_task_per_mou"
            ),
        ),
    ]
