# Generated by Django 6.1.1 on 2026-09-04 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0002_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="timerecord",
            name="task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_records",
                to="timetracking.task",
            ),
        ),
    ]
