# Generated by Django 6.1.1 on 2026-09-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0002_task_unique_task_per_mou"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="used_budget",
            field=models.FloatField(default=0.0),
        ),
    ]
