# Generated by Django 6.1.1 on 2026-09-04 11:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0003_task_used_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mou",
            name="name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="MoU name must not contain spaces.", regex="^\\S+$"
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False, max_length=80, primary_key=True, serialize=False
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "mou",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="timetracking.mou",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="timerecord",
            name="report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_records",
                to="timetracking.report",
            ),
        ),
    ]
