# Generated by Django 6.1.1 on 2026-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0004_alter_mou_name_report_timerecord_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="mou",
            name="budget",
            field=models.TextField(blank=True, default=""),
        ),
    ]
