# Generated by Django 6.1.1 on 2026-09-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0005_task_description_alter_mou_budget"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[("mou", "mou"), ("task", "task"), ("url", "url")],
                        max_length=8,
                    ),
                ),
                ("target", models.CharField(max_length=255)),
                ("alias", models.CharField(max_length=64)),
                (
                    "mou",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="timetracking.mou",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["item_type", "alias"],
                        name="timetrackin_item_ty_fd3244_idx",
                    )
                ],
            },
        ),
    ]
