# Generated by Django 6.1.1 on 2026-09-10 09:06, hand-edited to preserve data:
# existing TimeRecord.report associations are regrouped into ReportLine rows
# (one per report+link, budget computed from the grouped records' duration,
# tags seeded from the link's current tags) before the old field is dropped.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def group_into_report_lines(apps, schema_editor):
    TimeRecord = apps.get_model("timetracking", "TimeRecord")
    ReportLine = apps.get_model("timetracking", "ReportLine")

    lines_by_key = {}
    records = TimeRecord.objects.filter(
        report__isnull=False, link__isnull=False
    ).order_by("pk")
    for record in records:
        key = (record.report_id, record.link_id)
        line = lines_by_key.get(key)
        if line is None:
            tag_names = list(
                record.link.tags.order_by("name").values_list("name", flat=True)
            )
            line = ReportLine.objects.create(
                report_id=record.report_id,
                link_id=record.link_id,
                budget=0.0,
                tags=",".join(tag_names),
            )
            lines_by_key[key] = line
        record.report_line = line
        record.save(update_fields=["report_line"])

    rfp_euros = getattr(settings, "RFP_EUROS", None)
    for line in ReportLine.objects.all():
        total_seconds = 0.0
        for record in line.time_records.all():
            end = record.end_time or timezone.now()
            total_seconds += (end - record.start_time).total_seconds()
        line.budget = total_seconds / 3600 * rfp_euros if rfp_euros is not None else 0.0
        line.save(update_fields=["budget"])


def ungroup_report_lines(apps, schema_editor):
    TimeRecord = apps.get_model("timetracking", "TimeRecord")
    for record in TimeRecord.objects.filter(report_line__isnull=False):
        record.report_id = record.report_line.report_id
        record.save(update_fields=["report"])


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0006_alias"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget", models.FloatField(default=0.0)),
                ("tags", models.CharField(blank=True, default="", max_length=255)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_lines",
                        to="timetracking.link",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="timetracking.report",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="timerecord",
            name="report_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_records",
                to="timetracking.reportline",
            ),
        ),
        migrations.AddConstraint(
            model_name="reportline",
            constraint=models.UniqueConstraint(
                fields=("report", "link"), name="unique_report_line"
            ),
        ),
        migrations.RunPython(group_into_report_lines, ungroup_report_lines),
        migrations.RemoveField(
            model_name="timerecord",
            name="report",
        ),
    ]
