# Generated by Django 6.1.1 on 2026-09-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0007_remove_timerecord_report_reportline_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="excluded_from_reports",
            field=models.BooleanField(default=False),
        ),
    ]
