# Generated by Django 6.1.1 on 2026-09-10 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0008_link_excluded_from_reports"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="title",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
