# Generated by Django 6.1.1 on 2026-10-01 06:16

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import nlnet_rfp_recorder.alias_types


class Migration(migrations.Migration):
    dependencies = [
        ("timetracking", "0013_link_unique_nonempty_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alias",
            name="alias",
            field=models.CharField(
                help_text="The short nickname typed instead of `target`.", max_length=64
            ),
        ),
        migrations.AlterField(
            model_name="alias",
            name="item_type",
            field=models.CharField(
                choices=[
                    (
                        nlnet_rfp_recorder.alias_types.AliasItemType["MOU"],
                        nlnet_rfp_recorder.alias_types.AliasItemType["MOU"],
                    ),
                    (
                        nlnet_rfp_recorder.alias_types.AliasItemType["TASK"],
                        nlnet_rfp_recorder.alias_types.AliasItemType["TASK"],
                    ),
                    (
                        nlnet_rfp_recorder.alias_types.AliasItemType["URL"],
                        nlnet_rfp_recorder.alias_types.AliasItemType["URL"],
                    ),
                ],
                help_text="What kind of thing this alias names: 'mou', 'task', or 'url'.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="alias",
            name="mou",
            field=models.ForeignKey(
                blank=True,
                help_text="The MoU this alias is scoped to - only set for item_type='task', since task codes can repeat across MoUs.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                to="timetracking.mou",
            ),
        ),
        migrations.AlterField(
            model_name="alias",
            name="target",
            field=models.CharField(
                help_text="The real MoU name, task code, or repo base URL this alias stands in for.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="githubtoken",
            name="token",
            field=models.CharField(
                help_text="A GitHub personal access token, used to raise the API rate limit for issue/PR status checks. Set via `rfp token`.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="excluded_from_reports",
            field=models.BooleanField(
                default=False,
                help_text="Set when the user decides, on removing this link from a report during `report import`, that its time should never be offered for a report again - not merely 'not yet reported'. See Task.links_with_unreported_time.",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="How this link's time counts, e.g. 'implementation' or 'review'.",
                related_name="links",
                to="timetracking.tag",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="task",
            field=models.ForeignKey(
                blank=True,
                help_text="The task this link's tracked time counts toward, or None if unassigned.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="links",
                to="timetracking.task",
            ),
        ),
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Cached issue/PR title, fetched from GitHub once (see Report.ensure_link_titles) and kept indefinitely - blank means not fetched yet (or not an issue/PR), not 'known to have no title'.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="mou",
            name="budget",
            field=models.TextField(
                blank=True,
                default="",
                help_text="The raw text of the last budget document imported via `rfp mou import` (a whole milestone table or takentaal document, not a short value - unbounded rather than a short CharField), used to regenerate each task's budget and shown by `rfp mou export`.",
            ),
        ),
        migrations.AlterField(
            model_name="mou",
            name="name",
            field=models.CharField(
                help_text="The MoU's identifier, e.g. 'nlnet-2026'. Must not contain spaces.",
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="MoU name must not contain spaces.", regex="^\\S+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mou",
            name="selected",
            field=models.BooleanField(
                default=True,
                help_text="Whether this is the currently selected MoU (`rfp mou select`/`add`) - at most one MoU is selected at a time.",
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, help_text="When this report was generated."
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="id",
            field=models.CharField(
                editable=False,
                help_text="This report's id, '<MoU name>-<n>', numbered per MoU starting at 1.",
                max_length=80,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="report",
            name="mou",
            field=models.ForeignKey(
                blank=True,
                help_text="The MoU this report was generated for, or None if its MoU was removed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports",
                to="timetracking.mou",
            ),
        ),
        migrations.AlterField(
            model_name="reportline",
            name="budget",
            field=models.FloatField(
                default=0.0,
                help_text="This line's locked-in budget (EUR), snapshotted from tracked time when added and editable via `report import`.",
            ),
        ),
        migrations.AlterField(
            model_name="reportline",
            name="link",
            field=models.ForeignKey(
                help_text="The link (issue/PR/etc.) this line reports on.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="report_lines",
                to="timetracking.link",
            ),
        ),
        migrations.AlterField(
            model_name="reportline",
            name="report",
            field=models.ForeignKey(
                help_text="The report this line belongs to.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="timetracking.report",
            ),
        ),
        migrations.AlterField(
            model_name="reportline",
            name="tags",
            field=models.CharField(
                blank=True,
                default="",
                help_text="This line's tags, a snapshot of the link's tags taken when it was added - a report-scoped copy, editable independently via `report import` without affecting the link's own tags.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                choices=[("implementation", "implementation"), ("review", "review")],
                help_text="The tag name: 'implementation' or 'review'.",
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Free-text description of the task, shown by `rfp task status`/`select` and `rfp task list`.",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="max_budget",
            field=models.FloatField(
                blank=True,
                help_text="The maximum amount (EUR) the MoU allows for this task, e.g. as imported from a milestone budget table.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="mou",
            field=models.ForeignKey(
                blank=True,
                help_text="The MoU this task belongs to, or None if its MoU was removed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="timetracking.mou",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(
                help_text="The task's code as used in the MoU budget, e.g. '10a' (a number followed by letters).",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Task name must look like '10a': a number followed by letters.",
                        regex="^\\d+[a-z]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="personal_budget",
            field=models.FloatField(
                blank=True,
                help_text="The amount (EUR) you've personally decided to spend on this task, up to max_budget - used as the budget_line total for completion/time-left purposes. Set via `rfp task set --budget`. Falls back to max_budget when unset - see effective_personal_budget.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="selected",
            field=models.BooleanField(
                default=True,
                help_text="Whether this is the currently selected task (`rfp task select`) - at most one task is selected at a time.",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="used_budget",
            field=models.FloatField(
                default=0.0,
                help_text="Budget (EUR) already spent on this task before this tool started tracking it, e.g. from an earlier milestone report. Set via `rfp mou import` or `rfp task set used`.",
            ),
        ),
        migrations.AlterField(
            model_name="timerecord",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="When this time entry stopped, or None while it's still running.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="timerecord",
            name="link",
            field=models.ForeignKey(
                blank=True,
                help_text="The link this time entry was tracked against, or None if it has none.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_records",
                to="timetracking.link",
            ),
        ),
        migrations.AlterField(
            model_name="timerecord",
            name="report_line",
            field=models.ForeignKey(
                blank=True,
                help_text="The report line this time entry has been claimed by, or None if unreported.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_records",
                to="timetracking.reportline",
            ),
        ),
        migrations.AlterField(
            model_name="timerecord",
            name="start_time",
            field=models.DateTimeField(help_text="When this time entry started."),
        ),
    ]
